#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=10GB,walltime=00:05:00
#PBS -N test

set -e
set -x

time singularity exec -e docker://python ./test.py

cat > product.json <<EOF
{
    "output": {
        "tags": [
            "from_app"
        ],
        "meta": {
            "thing": "from product.json"
        }
    },
    "brainlife": {}
}
EOF
