#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=10GB,walltime=00:05:00
#PBS -N test

set -e
set -x

anat=$(jq -r .t1 config.json)

time singularity exec -e docker://python ./test.py

mkdir -p anat
install $anat anat/t1.nii.gz

cat > product.json <<EOF
{
    "anat": {
        "tags": [
            "from_app"
        ],
        "meta": {
            "thing": "from product.json"
        }
    },
    "brainlife": {}
}
EOF
